# NumPy Exercises 



#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 fives

In [3]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [4]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [5]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [7]:
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy to generate a random number between 0 and 1

In [8]:
b = np.random.random(1)
b


array([0.85227634])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [9]:
b = np.random.standard_normal(25)
b.mean()
b.std()
b

array([-1.47994157, -0.95926742, -0.33427368,  0.59689042,  0.4901039 ,
       -0.40327335,  0.25616122, -0.66729754,  0.55334989,  0.47541281,
       -0.87628919, -0.76986492, -0.63861281, -0.40636262, -0.1635137 ,
       -0.15705021, -1.56054747, -0.46910692, -0.52793196, -0.58273708,
        0.32542104, -0.76167575, -0.23706208, -0.80534555,  0.0597304 ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [10]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Numpy 3d array (3 rows, 4 cols, 2 layer)

In [19]:
x = np.random.random((3,4,2))
x[:,:,1]

array([[0.27289711, 0.8947984 , 0.6700466 , 0.31658146],
       [0.86810326, 0.99788715, 0.04376641, 0.33349304],
       [0.56319409, 0.08835237, 0.60581966, 0.05258199]])

## Numpy Indexing and Selection

Create the following 2D matrix. 

[ 1,  2,  3,  4,  5]
[ 6,  7,  8,  9, 10]
[11, 12, 13, 14, 15]
[16, 17, 18, 19, 20]
[21, 22, 23, 24, 25]

In [22]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in matrix

#### Get the standard deviation of the values in matrix

#### Get the sum of all the columns in matrix